
application:
  name: nginx-upload
  project: nginx-upload
  cloud_region: aws/eu-west-3
  publicly_accessible: true
routers:
  - name: main
    routes:
      - application_name: nginx-upload
        paths:
          - /*
